spring:
  application:
    name: ganjoorak
  ai:
    google:
      genai:
        project-id: ai-dev-tools-prod-57391
        location: europe-west1
        chat:
          options:
            model: gemini-2.5-pro
            google-search-retrieval: true
            temperature: 0.01
        vertex-ai: true

  main:
    banner-mode: off
  http:
    client:
      factory: jdk
  datasource:
    url: jdbc:sqlite::resource:ganjoor.s3db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      connection-test-query: SELECT 1
server:
  compression:
    enabled: true
    mime-types: application/json,text/html,text/css,application/javascript
    min-response-size: 1024
